/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.15
 * Generated at: 2025-12-21 07:24:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vista;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class FormularioPaciente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Modal Paciente -->\r\n");
      out.write("<div class=\"modal fade\" id=\"modalPaciente\" tabindex=\"-1\" aria-labelledby=\"modalPacienteLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"modalPacienteLabel\">\r\n");
      out.write("                    <i class=\"fas fa-user-plus me-2\"></i>\r\n");
      out.write("                    Nuevo Paciente\r\n");
      out.write("                </h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form id=\"formPaciente\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"pacienteId\" name=\"id\">\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- DATOS PERSONALES -->\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <i class=\"fas fa-user me-2\"></i>Datos Personales\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"nombre\" class=\"form-label required-field\">Nombre</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"nombre\" name=\"nombre\" \r\n");
      out.write("                                   placeholder=\"Ej. Juan Carlos\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"apellido\" class=\"form-label required-field\">Apellido</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"apellido\" name=\"apellido\" \r\n");
      out.write("                                   placeholder=\"Ej. Pérez López\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"cedula\" class=\"form-label required-field\">Cédula</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"cedula\" name=\"cedula\" \r\n");
      out.write("                                   placeholder=\"0123456789\" maxlength=\"10\" required>\r\n");
      out.write("                            <small class=\"text-muted\">Cédula ecuatoriana de 10 dígitos</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"fechaNacimiento\" class=\"form-label required-field\">Fecha de Nacimiento</label>\r\n");
      out.write("                            <input type=\"date\" class=\"form-control\" id=\"fechaNacimiento\" name=\"fechaNacimiento\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- DATOS DE CONTACTO -->\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <i class=\"fas fa-address-book me-2\"></i>Datos de Contacto\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"celular\" class=\"form-label\">Celular</label>\r\n");
      out.write("                            <input type=\"tel\" class=\"form-control\" id=\"celular\" name=\"telefono\" \r\n");
      out.write("                                   placeholder=\"0991234567\" maxlength=\"10\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <label for=\"email\" class=\"form-label\">Correo Electrónico</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" \r\n");
      out.write("                                   placeholder=\"ejemplo@correo.com\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                            <label for=\"direccion\" class=\"form-label\">Dirección</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"direccion\" name=\"direccion\" \r\n");
      out.write("                                   placeholder=\"Calle, número, sector\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"ocupacion\" class=\"form-label\">Ocupación</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"ocupacion\" name=\"ocupacion\" \r\n");
      out.write("                                   placeholder=\"Ej. Profesor\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- PERFIL CLÍNICO -->\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <i class=\"fas fa-notes-medical me-2\"></i>Perfil Clínico / Antecedentes\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"antecedentesOculares\" class=\"form-label\">Antecedentes Oculares</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"antecedentesOculares\" name=\"antecedentesOculares\" \r\n");
      out.write("                                      rows=\"2\" placeholder=\"Ej. Cirugía de cataratas en 2020, conjuntivitis recurrente...\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"antecedentesMedicos\" class=\"form-label\">Antecedentes Médicos</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"antecedentesMedicos\" name=\"antecedentesMedicos\" \r\n");
      out.write("                                      rows=\"2\" placeholder=\"Ej. Diabetes tipo 2, hipertensión arterial...\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"antecedentesFamiliares\" class=\"form-label\">Antecedentes Familiares</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"antecedentesFamiliares\" name=\"antecedentesFamiliares\" \r\n");
      out.write("                                      rows=\"2\" placeholder=\"Ej. Padre con glaucoma, madre con miopía alta...\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"antecedentesFarmacologicos\" class=\"form-label\">Antecedentes Farmacológicos</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"antecedentesFarmacologicos\" name=\"antecedentesFarmacologicos\" \r\n");
      out.write("                                      rows=\"2\" placeholder=\"Ej. Metformina 850mg cada 12h, Losartán 50mg...\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                    <i class=\"fas fa-times me-2\"></i>Cancelar\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-orange\" onclick=\"guardarPaciente()\">\r\n");
      out.write("                    <i class=\"fas fa-save me-2\"></i>Guardar Paciente\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
