/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.15
 * Generated at: 2025-12-21 17:05:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vista;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ListaPacientes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/MY%20LENOVO/OneDrive/Documentos/UNIVERSIDAD/Sexto%20Semestre/App_Web/Web_Optica/codigo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/opticaLV/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld", Long.valueOf(1664471478000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1759525377379L));
    _jspx_dependants.put("jar:file:/C:/Users/MY%20LENOVO/OneDrive/Documentos/UNIVERSIDAD/Sexto%20Semestre/App_Web/Web_Optica/codigo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/opticaLV/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664471478000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Pacientes - Óptica Latitud Visual</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <nav class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-header\">\r\n");
      out.write("            <a href=\"#\" class=\"brand-badge\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/logo.png\" alt=\"logo\" class=\"sidebar-logo-img\">\r\n");
      out.write("                <div class=\"d-flex flex-column\">\r\n");
      out.write("                    <span class=\"brand-text-small\">OPTICA</span>\r\n");
      out.write("                    <span class=\"brand-text-main\">LATITUD VISUAL</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sidebar-menu\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pacientes\" class=\"nav-link active\">\r\n");
      out.write("                <i class=\"fa fa-users\"></i> Pacientes\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/inventario\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"fa fa-boxes\"></i> Inventario\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/servicios\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"fa fa-concierge-bell\"></i> Servicios\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ventas\" class=\"nav-link\"> \r\n");
      out.write("                <i class=\"fas fa-cash-register\"></i> Ventas\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fichas\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"fa fa-file-medical\"></i> Fichas Clínicas\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"sidebar-footer\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout-link\">\r\n");
      out.write("                <i class=\"fa fa-sign-out-alt me-3\"></i> Cerrar sesión\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"top-header\">\r\n");
      out.write("        <h4 class=\"mb-0 fw-bold text-dark\">Dashboard</h4>\r\n");
      out.write("        <div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("            <div class=\"text-end\">\r\n");
      out.write("                <div class=\"fw-bold\">Dra. Cumanda Delgado</div>\r\n");
      out.write("                <small class=\"text-muted\">Administrador</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img src=\"https://ui-avatars.com/api/?name=Cumanda+Delgado&background=0a2342&color=fff\" \r\n");
      out.write("                 class=\"rounded-circle\" width=\"40\" height=\"40\" alt=\"Avatar\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <h2 class=\"page-title\">Pacientes</h2>\r\n");
      out.write("\r\n");
      out.write("        <!-- Barra de búsqueda y botón agregar -->\r\n");
      out.write("        <div class=\"row mb-4 align-items-center\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"input-group shadow-sm\">\r\n");
      out.write("                    <span class=\"input-group-text bg-white ps-3\">\r\n");
      out.write("                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <input type=\"text\" id=\"searchInput\" class=\"form-control py-2\" \r\n");
      out.write("                           placeholder=\"Buscar por Cédula o Nombre\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write(" \r\n");
      out.write("            <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                <button class=\"btn btn-orange\" onclick=\"abrirModalNuevo()\">\r\n");
      out.write("                    <i class=\"fas fa-user-plus\"></i> Nuevo Paciente\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Tabla de pacientes -->\r\n");
      out.write("        <div class=\"card-table\">\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table table-hover align-middle mb-0\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Nombre Completo</th>\r\n");
      out.write("                            <th>Cédula</th>\r\n");
      out.write("                            <th>Celular</th>\r\n");
      out.write("                            <th>Correo</th>\r\n");
      out.write("                            <th class=\"text-end\">Acciones</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("					<tbody id=\"tablaPacientes\">\r\n");
      out.write("					    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal Paciente -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FormularioPaciente.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    const contextPath = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    \r\n");
      out.write("    // Búsqueda en tiempo real\r\n");
      out.write("    let searchTimeout;\r\n");
      out.write("    document.getElementById('searchInput').addEventListener('input', function(e) {\r\n");
      out.write("        clearTimeout(searchTimeout);\r\n");
      out.write("        searchTimeout = setTimeout(() => {\r\n");
      out.write("            listarPacientes(e.target.value);\r\n");
      out.write("        }, 500);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function listarPacientes(criterio = '') {\r\n");
      out.write("        // Usamos accion=buscar para obtener JSON\r\n");
      out.write("        const url = contextPath + '/pacientes?accion=buscar&criterio=' + encodeURIComponent(criterio);\r\n");
      out.write("        \r\n");
      out.write("        fetch(url)\r\n");
      out.write("            .then(response => {\r\n");
      out.write("                if (!response.ok) throw new Error(\"Error en la red\");\r\n");
      out.write("                return response.json();\r\n");
      out.write("            })\r\n");
      out.write("            .then(pacientes => {\r\n");
      out.write("                actualizarTabla(pacientes);\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                console.error('Error al listar:', error);\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function actualizarTabla(pacientes) {\r\n");
      out.write("        const tbody = document.getElementById('tablaPacientes');\r\n");
      out.write("        \r\n");
      out.write("        if (pacientes.length === 0) {\r\n");
      out.write("            tbody.innerHTML = `\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"5\" class=\"text-center text-muted py-4\">\r\n");
      out.write("                        <i class=\"fas fa-search fa-2x mb-2\"></i>\r\n");
      out.write("                        <p>No se encontraron pacientes</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>`;\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Renderizado de filas\r\n");
      out.write("        tbody.innerHTML = pacientes.map(p => `\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div class=\"fw-bold\">${p.nombre} ${p.apellido}</div>\r\n");
      out.write("                    <small class=\"text-muted\">${calcularEdad(p.fechaNacimiento)} Años</small>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div>${p.cedula}</div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div>${p.telefono ? p.telefono : '-'}</div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <span class=\"text-muted\">\r\n");
      out.write("                        ${p.correoElectronico ? p.correoElectronico : '-'}\r\n");
      out.write("                    </span>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"text-end\">\r\n");
      out.write("                    <button class=\"btn btn-light text-primary shadow-sm\" \r\n");
      out.write("                            title=\"Editar\" onclick=\"editarPaciente(${p.id})\">\r\n");
      out.write("                        <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"btn btn-light text-danger shadow-sm\" \r\n");
      out.write("                            title=\"Eliminar\" onclick=\"confirmarEliminar(${p.id}, '${p.nombre} ${p.apellido}')\">\r\n");
      out.write("                        <i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        `).join('');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function calcularEdad(fecha) {\r\n");
      out.write("        if(!fecha) return 0;\r\n");
      out.write("        const hoy = new Date();\r\n");
      out.write("        const nacimiento = new Date(fecha);\r\n");
      out.write("        let edad = hoy.getFullYear() - nacimiento.getFullYear();\r\n");
      out.write("        const mes = hoy.getMonth() - nacimiento.getMonth();\r\n");
      out.write("        if (mes < 0 || (mes === 0 && hoy.getDate() < nacimiento.getDate())) {\r\n");
      out.write("            edad--;\r\n");
      out.write("        }\r\n");
      out.write("        return edad;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function abrirModalNuevo() {\r\n");
      out.write("        document.getElementById('formPaciente').reset();\r\n");
      out.write("        document.getElementById('pacienteId').value = '';\r\n");
      out.write("        document.getElementById('modalPacienteLabel').innerHTML = \r\n");
      out.write("            '<i class=\"fas fa-user-plus me-2\"></i>Nuevo Paciente';\r\n");
      out.write("        \r\n");
      out.write("        const modal = new bootstrap.Modal(document.getElementById('modalPaciente'));\r\n");
      out.write("        modal.show();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function editarPaciente(id) {\r\n");
      out.write("        if (!id) {\r\n");
      out.write("            console.error(\"ID inválido para editar\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        const url = contextPath + \"/pacientes?accion=obtener&id=\" + id;\r\n");
      out.write("        \r\n");
      out.write("        fetch(url)\r\n");
      out.write("            .then(response => {\r\n");
      out.write("                if (!response.ok) throw new Error(\"Error al obtener paciente\");\r\n");
      out.write("                return response.json();\r\n");
      out.write("            })\r\n");
      out.write("            .then(paciente => {\r\n");
      out.write("                document.getElementById('pacienteId').value = paciente.id;\r\n");
      out.write("                document.getElementById('nombre').value = paciente.nombre;\r\n");
      out.write("                document.getElementById('apellido').value = paciente.apellido;\r\n");
      out.write("                document.getElementById('cedula').value = paciente.cedula;\r\n");
      out.write("                document.getElementById('fechaNacimiento').value = paciente.fechaNacimiento;\r\n");
      out.write("                // Manejo seguro de nulos para los campos opcionales\r\n");
      out.write("                document.getElementById('celular').value = paciente.telefono || '';\r\n");
      out.write("                document.getElementById('email').value = paciente.correoElectronico || '';\r\n");
      out.write("                document.getElementById('direccion').value = paciente.direccion || '';\r\n");
      out.write("                document.getElementById('ocupacion').value = paciente.ocupacion || '';\r\n");
      out.write("                document.getElementById('antecedentesOculares').value = paciente.antecedentesOculares || '';\r\n");
      out.write("                document.getElementById('antecedentesMedicos').value = paciente.antecedentesMedicos || '';\r\n");
      out.write("                document.getElementById('antecedentesFamiliares').value = paciente.antecedentesFamiliares || '';\r\n");
      out.write("                document.getElementById('antecedentesFarmacologicos').value = paciente.antecedentesFarmacologicos || '';\r\n");
      out.write("                \r\n");
      out.write("                document.getElementById('modalPacienteLabel').innerHTML = \r\n");
      out.write("                    '<i class=\"fas fa-user-edit me-2\"></i>Editar Paciente';\r\n");
      out.write("                \r\n");
      out.write("                const modal = new bootstrap.Modal(document.getElementById('modalPaciente'));\r\n");
      out.write("                modal.show();\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                console.error('Error:', error);\r\n");
      out.write("                Swal.fire('Error', 'No se pudo cargar la información del paciente', 'error');\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function guardarPaciente() {\r\n");
      out.write("        const form = document.getElementById('formPaciente');\r\n");
      out.write("        if (!form.checkValidity()) {\r\n");
      out.write("            form.reportValidity();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        const formData = new FormData(form);\r\n");
      out.write("        const id = document.getElementById('pacienteId').value;\r\n");
      out.write("        formData.append('accion', id ? 'editar' : 'guardar');\r\n");
      out.write("        if (id) {\r\n");
      out.write("            formData.append('id', id);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        fetch(contextPath + '/pacientes', {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            body: formData\r\n");
      out.write("        })\r\n");
      out.write("        // ------------------------\r\n");
      out.write("        .then(response => {\r\n");
      out.write("             if(!response.ok) throw new Error(\"Error en la petición: \" + response.status);\r\n");
      out.write("             return response.json();\r\n");
      out.write("        })\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            if (data.success === 'true') {\r\n");
      out.write("                // Cerrar modal\r\n");
      out.write("                const modalElement = document.getElementById('modalPaciente');\r\n");
      out.write("                const modalInstance = bootstrap.Modal.getInstance(modalElement);\r\n");
      out.write("                modalInstance.hide();\r\n");
      out.write("                \r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'success',\r\n");
      out.write("                    title: '¡Éxito!',\r\n");
      out.write("                    text: data.message,\r\n");
      out.write("                    timer: 1500,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                listarPacientes('');\r\n");
      out.write("            } else {\r\n");
      out.write("                Swal.fire('Error', data.message, 'error');\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch(error => {\r\n");
      out.write("            console.error('Error:', error);\r\n");
      out.write("            Swal.fire('Error', 'Ocurrió un error al guardar.', 'error');\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function confirmarEliminar(id, nombre) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            title: '¿Está seguro?',\r\n");
      out.write("            text: `¿Desea eliminar al paciente ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nombre}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("?`,\r\n");
      out.write("            icon: 'warning',\r\n");
      out.write("            showCancelButton: true,\r\n");
      out.write("            confirmButtonColor: '#d33',\r\n");
      out.write("            cancelButtonColor: '#3085d6',\r\n");
      out.write("            confirmButtonText: 'Sí, eliminar',\r\n");
      out.write("            cancelButtonText: 'Cancelar'\r\n");
      out.write("        }).then((result) => {\r\n");
      out.write("            if (result.isConfirmed) {\r\n");
      out.write("                eliminarPaciente(id);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function eliminarPaciente(id) {\r\n");
      out.write("        const formData = new FormData();\r\n");
      out.write("        formData.append('accion', 'eliminar');\r\n");
      out.write("        formData.append('id', id);\r\n");
      out.write("\r\n");
      out.write("        fetch(contextPath + '/pacientes', {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            body: formData\r\n");
      out.write("        })\r\n");
      out.write("        .then(response => {\r\n");
      out.write("            if(!response.ok) throw new Error(\"Error en la petición\");\r\n");
      out.write("            return response.json();\r\n");
      out.write("        })\r\n");
      out.write("        .then(data => {\r\n");
      out.write("            if (data.success === 'true') {\r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    icon: 'success',\r\n");
      out.write("                    title: '¡Eliminado!',\r\n");
      out.write("                    text: data.message,\r\n");
      out.write("                    timer: 1500,\r\n");
      out.write("                    showConfirmButton: false\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                // Recargar la tabla\r\n");
      out.write("                listarPacientes('');\r\n");
      out.write("            } else {\r\n");
      out.write("                Swal.fire('Error', data.message, 'error');\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch(error => {\r\n");
      out.write("            console.error('Error:', error);\r\n");
      out.write("            Swal.fire('Error', 'Ocurrió un error al eliminar', 'error');\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /vista/ListaPacientes.jsp(101,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty pacientes}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("					        <tr>\r\n");
        out.write("					            <td colspan=\"5\" class=\"text-center text-muted py-4\">\r\n");
        out.write("					                <i class=\"fas fa-search fa-2x mb-2\"></i>\r\n");
        out.write("					                <p>No se encontraron pacientes registrados</p>\r\n");
        out.write("					            </td>\r\n");
        out.write("					        </tr>\r\n");
        out.write("					    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /vista/ListaPacientes.jsp(110,9) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/vista/ListaPacientes.jsp(110,9) '${pacientes}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pacientes}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /vista/ListaPacientes.jsp(110,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("paciente");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					        <tr>\r\n");
          out.write("					            <td>\r\n");
          out.write("					                <div class=\"fw-bold\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.nombreCompleto}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("					                <small class=\"text-muted\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.edad}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" Años</small>\r\n");
          out.write("					            </td>\r\n");
          out.write("					            <td>\r\n");
          out.write("					                <div>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.cedula}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("					            </td>\r\n");
          out.write("					            <td>\r\n");
          out.write("					                <div>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.telefono != null ? paciente.telefono : '-'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("					            </td>\r\n");
          out.write("					            <td>\r\n");
          out.write("					                <span class=\"text-muted\">\r\n");
          out.write("					                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.correoElectronico != null ? paciente.correoElectronico : '-'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("					                </span>\r\n");
          out.write("					            </td>\r\n");
          out.write("					            <td class=\"text-end\">\r\n");
          out.write("					                <button class=\"btn btn-light text-primary shadow-sm\" \r\n");
          out.write("					                        title=\"Editar\" onclick=\"editarPaciente(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("					                    <i class=\"fas fa-edit\"></i>\r\n");
          out.write("					                </button>\r\n");
          out.write("					                <button class=\"btn btn-light text-danger shadow-sm\" \r\n");
          out.write("					                        title=\"Eliminar\" onclick=\"confirmarEliminar(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(',');
          out.write(' ');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paciente.nombreCompleto}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">\r\n");
          out.write("					                    <i class=\"fas fa-trash-alt\"></i>\r\n");
          out.write("					                </button>\r\n");
          out.write("					            </td>\r\n");
          out.write("					        </tr>\r\n");
          out.write("					    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
